### ISSUE TITLE
Rpi camera v2 not detected

### ISSUE THREAD

**Issue by bdudout** [FarmBot-Labs/Take-Photo#2]
Hello,

I tested this farmware with 2 different rpi3 and 2 different rpi camera v2 (made in UK/made in PRC) the camera is connected via ribbon cable.

When I use the camera on a rpi3 running Raspian I can get pics and vids with _raspistill_ and _raspivid_ and when calling vcgencmd I get the confirmation my camera is working fine.

```
 vcgencmd get_camera
 supported=1 detected=1
```

The farmware is using os.version to detect the camera, but on my system it does not contain the key "camera" therefore the farmware is going for the USB camera.

I wanted to check for vcgencmd get_camera instead of using os.version in the farmware, but the command vcgencmd is not installed on Farmbot OS.

```
        out=subprocess.check_output(['vcgencmd','get_camera'])
        dict=dict(s.split('=') for s in out.rstrip().split(' '))
        supported=dict['supported']
        detected=dict['detected']
```

 So I added a call to rpi_camera_photo() in case the USB camera detection is not working, but it's not the prettiest way to do it. https://github.com/bdudout/take-photo/blob/master/take_photo.py

**Comment by gabrielburnworth** [comment]
Did you choose the `Raspberry Pi Camera` in the Camera selection drop-down in the Device widget? It's on the `Device` page of the web app at staging.farmbot.io.

**Comment by bdudout** [comment]
Thanks!
I was testing with my.farmbot.io so I couldn't see this dropdown until now.
