### ISSUE TITLE
Does not take photos.

### ISSUE THREAD

**Issue by waldenhillegass** [FarmBot-Labs/Take-Photo#7]
Please make some kind of better logging for taking photos. It is being inconsistent and I have no idea why.

**Comment by gabrielburnworth** [comment]
Thanks for the issue! I've made several logging and error handling improvements, hopefully those help. Some background:

There are currently logs provided for information that is available to the script about image capture failures including:
 - camera is missing or unplugged
 - no image was returned from the camera

There are also logs provided for environment issues including missing directories and import errors.

If you don't currently have console access, additional internal V4L logs not accessible to the script in this repository are available via a USB to TTY cable. These logs rarely provide further information about why an image was not returned (i.e., "select timeout" for the "problem getting image" logs), but do occasionally ("resource busy" if the camera is already in use). The recently added additional runtime logs are also available for viewing from console.

The resolution in cases where no image is returned is usually the same: check the camera connections, unplug and plug in the camera (into a different port if possible), or replace the camera if it is broken or defective.

Any details you can provide about your use case, environment, or what you have experienced with your camera may be helpful. This may include: platform or system running this script, type of camera used, and type of failure or log messages experienced.

For future readers: if you have not done so already, I would encourage you to contact contact@farmbot.io if you are a FarmBot customer (replacements for defective parts are available free of charge to FarmBot customers) or make use of the forum at https://forum.farmbot.org for assistance.
